#ifndef __MADC32_H__
#define __MADC32_H__

/*_______________________________________________________________[HEADER FILE]
//////////////////////////////////////////////////////////////////////////////
//! \file			madc32.h
//! \brief			Definitions for Mesytec Madc32 ADC
//! \details		Contains definitions to operate a Mesytec Madc32
//! $Author: Marabou $
//! $Mail:			<a href=mailto:rudi.lutter@physik.uni-muenchen.de>R. Lutter</a>$
//! $Revision: 1.15 $
//! $Date: 2011-04-29 07:19:03 $
////////////////////////////////////////////////////////////////////////////*/

#define MADC32_THRESHOLD				0x4000

#define MADC32_BANK_OPERATION			0x6040
#define MADC32_ADC_RESOLUTION			0x6042
#define MADC32_OUTPUT_FORMAT			0x6044
#define MADC32_ADC_OVERRIDE				0x6046
#define MADC32_SLIDING_SCALE_OFF		0x6048
#define MADC32_SKIP_OUT_OF_RANGE		0x604A
#define MADC32_IGNORE_THRESHOLDS		0x604C

#define MADC32_GG_HOLD_DELAY_0 			0x6050
#define MADC32_GG_HOLD_DELAY_1 			0x6052
#define MADC32_GG_HOLD_WIDTH_0 			0x6054
#define MADC32_GG_HOLD_WIDTH_1 			0x6056
#define MADC32_USE_GATE_GENERATOR		0x6058

#define MADC32_INPUT_RANGE 				0x6060
#define MADC32_ECL_TERMINATORS			0x6062
#define MADC32_ECL_G1_OSC				0x6064
#define MADC32_ECL_FCL_RTS				0x6066
#define MADC32_ECL_BUSY					0x6068
#define MADC32_NIM_G1_OSC				0x606A
#define MADC32_NIM_FCL_RTS				0x606C
#define MADC32_NIM_BUSY					0x606E

#define MADC32_PULSER_STATUS			0x6070

#define MADC32_THRESHOLD_DEFAULT		0
#define MADC32_THRESHOLD_MASK			0xFFF

#define MADC32_BANK_OPERATION_CON		0
#define MADC32_BANK_OPERATION_INDEP 1
#define MADC32_BANK_OPERATION_TOGGLE	3
#define MADC32_BANK_OPERATION_DEFAULT	MADC32_BANK_OPERATION_CON
#define MADC32_BANK_OPERATION_MASK  	MADC32_BANK_OPERATION_TOGGLE

#define MADC32_ADC_RESOLUTION_2K		0
#define MADC32_ADC_RESOLUTION_4K		1
#define MADC32_ADC_RESOLUTION_4K_HIRES	2
#define MADC32_ADC_RESOLUTION_8K		3
#define MADC32_ADC_RESOLUTION_8K_HIRES	4
#define MADC32_ADC_RESOLUTION_DEFAULT	MADC32_ADC_RESOLUTION_4K_HIRES
#define MADC32_ADC_RESOLUTION_MASK		0x7

#define MADC32_ADC_OVERWRITE_DEFAULT	5

#define MADC32_OUTPUT_FORMAT_MESY		0
#define MADC32_OUTPUT_FORMAT_RESRVD 	1
#define MADC32_OUTPUT_FORMAT_DEFAULT	MADC32_OUTPUT_FORMAT_MESY
#define MADC32_OUTPUT_FORMAT_MASK		MADC32_OUTPUT_FORMAT_RESRVD

#define MADC32_SLIDING_SCALE_OFF_MASK	0x1
#define MADC32_SKIP_OUT_OF_RANGE_MASK	0x1
#define MADC32_IGNORE_THRESH_MASK		0x1

#define MADC32_GG_HOLD_DELAY_DEFAULT	20
#define MADC32_GG_HOLD_DELAY_MASK		0xFF
#define MADC32_GG_HOLD_WIDTH_DEFAULT	50
#define MADC32_GG_HOLD_WIDTH_MASK		0xFF

#define MADC32_USE_GATE_GENERATOR_0 		0x1
#define MADC32_USE_GATE_GENERATOR_1 		0x2
#define MADC32_USE_GATE_GENERATOR_BOTH		(MADC32_USE_GATE_GENERATOR_0 | MADC32_USE_GATE_GENERATOR_1)
#define MADC32_USE_GATE_GENERATOR_DEFAULT	MADC32_USE_GATE_GENERATOR_0
#define MADC32_USE_GATE_GENERATOR_MASK		MADC32_USE_GATE_GENERATOR_BOTH

#define MADC32_INPUT_RANGE_4V				0
#define MADC32_INPUT_RANGE_10V				1
#define MADC32_INPUT_RANGE_8V				2
#define MADC32_INPUT_RANGE_DEFAULT 			MADC32_INPUT_RANGE_4V
#define MADC32_INPUT_RANGE_MASK 			0x3

#define MADC32_ECL_TERMINATORS_G0			0x1
#define MADC32_ECL_TERMINATORS_G1			0x2
#define MADC32_ECL_TERMINATORS_BUSY			0x4
#define MADC32_ECL_TERMINATORS_FCL			0x8
#define MADC32_ECL_TERMINATORS_DEFAULT  	(MADC32_ECL_TERMINATORS_G0 | MADC32_ECL_TERMINATORS_G1 | MADC32_ECL_TERMINATORS_BUSY | MADC32_ECL_TERMINATORS_FCL)
#define MADC32_ECL_TERMINATORS_MASK 		MADC32_ECL_TERMINATORS_DEFAULT

#define MADC32_ECL_INPUT_G1					0
#define MADC32_ECL_INPUT_OSC				1
#define MADC32_ECL_G1_OSC_DEFAULT			MADC32_ECL_INPUT_G1
#define MADC32_ECL_G1_OSC_MASK				MADC32_ECL_INPUT_OSC

#define MADC32_ECL_INPUT_FCL				0
#define MADC32_ECL_INPUT_RTS				1
#define MADC32_ECL_FCL_RTS_DEFAULT			MADC32_ECL_INPUT_FCL
#define MADC32_ECL_FCL_RTS_MASK				MADC32_ECL_INPUT_RTS

#define MADC32_NIM_INPUT_G1					0
#define MADC32_NIM_INPUT_OSC				1
#define MADC32_NIM_G1_OSC_DEFAULT			MADC32_NIM_INPUT_G1
#define MADC32_NIM_G1_OSC_MASK				MADC32_NIM_INPUT_OSC

#define MADC32_NIM_INPUT_FCL				0
#define MADC32_NIM_INPUT_RTS				1
#define MADC32_NIM_FCL_RTS_DEFAULT			MADC32_NIM_INPUT_FCL
#define MADC32_NIM_FCL_RTS_MASK				MADC32_NIM_INPUT_RTS

#define MADC32_NIM_BUSY_BUSY				0
#define MADC32_NIM_BUSY_G0					1
#define MADC32_NIM_BUSY_G1					2
#define MADC32_NIM_BUSY_CBUS				3
#define MADC32_NIM_BUSY_BUFFER_FULL			4
#define MADC32_NIM_BUSY_ABOVE_THRESH		8
#define MADC32_NIM_BUSY_DEFAULT				MADC32_NIM_BUSY_BUSY
#define MADC32_NIM_BUSY_MASK				0xF

#define MADC32_PULSER_OFF					0
#define MADC32_PULSER_A0					4
#define MADC32_PULSER_ALOW					5
#define MADC32_PULSER_AHIGH					6
#define MADC32_PULSER_A0LH0					7
#define MADC32_PULSER_STATUS_DEFAULT		MADC32_PULSER_OFF
#define MADC32_PULSER_STATUS_MASK			MADC32_PULSER_A0LH0

#endif
