//
// File generated by rootcint at Tue Nov 26 13:12:56 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME motorDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "motorDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::Motor Motor;
      #else
      class Motor  {
         public:
         //friend XX;
         #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
         typedef ::Motor::AXES AXES;
         #else
         enum AXES  {
         };
         #endif

         typedef ::Motor::AXES AXES;
         bool d_status; //
         int d_deviceNumber; //
         AXES d_activeAxes; //
         int* d_posX; //
         int* d_posY; //
         int* d_posZ; //
         int d_speedX; //
         int d_speedY; //
         int d_speedZ; //
         int d_minPosX; //
         int d_minPosY; //
         int d_minPosZ; //
         int d_maxPosX; //
         int d_maxPosY; //
         int d_maxPosZ; //
         int d_fd; //
         char d_error; //
         long d_bufferSize; //
         char d_buffer[128]; //
         int d_semId; //
         void* d_shmPtr; //
         bool d_debug; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Motor_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void Motor_Dictionary();
   static void *new_Motor(void *p = 0);
   static void *newArray_Motor(Long_t size, void *p);
   static void delete_Motor(void *p);
   static void deleteArray_Motor(void *p);
   static void destruct_Motor(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Motor*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::Motor) == sizeof(::ROOT::Shadow::Motor));
      ::Motor *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Motor),0);
      static ::ROOT::TGenericClassInfo 
         instance("Motor", "./motor.h", 12,
                  typeid(::Motor), DefineBehavior(ptr, ptr),
                  &Motor_ShowMembers, &Motor_Dictionary, isa_proxy, 4,
                  sizeof(::Motor) );
      instance.SetNew(&new_Motor);
      instance.SetNewArray(&newArray_Motor);
      instance.SetDelete(&delete_Motor);
      instance.SetDeleteArray(&deleteArray_Motor);
      instance.SetDestructor(&destruct_Motor);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Motor*)
   {
      return GenerateInitInstanceLocal((::Motor*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Motor*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Motor_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::Motor*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void Motor_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class Motor.
      typedef ::ROOT::Shadow::Motor ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::Motor*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_status", &sobj->d_status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_deviceNumber", &sobj->d_deviceNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_activeAxes", &sobj->d_activeAxes);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*d_posX", &sobj->d_posX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*d_posY", &sobj->d_posY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*d_posZ", &sobj->d_posZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_speedX", &sobj->d_speedX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_speedY", &sobj->d_speedY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_speedZ", &sobj->d_speedZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_minPosX", &sobj->d_minPosX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_minPosY", &sobj->d_minPosY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_minPosZ", &sobj->d_minPosZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_maxPosX", &sobj->d_maxPosX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_maxPosY", &sobj->d_maxPosY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_maxPosZ", &sobj->d_maxPosZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_fd", &sobj->d_fd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_error", &sobj->d_error);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_bufferSize", &sobj->d_bufferSize);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_buffer[128]", sobj->d_buffer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_semId", &sobj->d_semId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*d_shmPtr", &sobj->d_shmPtr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "d_debug", &sobj->d_debug);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Motor(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Motor : new ::Motor;
   }
   static void *newArray_Motor(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Motor[nElements] : new ::Motor[nElements];
   }
   // Wrapper around operator delete
   static void delete_Motor(void *p) {
      delete ((::Motor*)p);
   }
   static void deleteArray_Motor(void *p) {
      delete [] ((::Motor*)p);
   }
   static void destruct_Motor(void *p) {
      typedef ::Motor current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Motor

/********************************************************
* motorDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemotorDict();

extern "C" void G__set_cpp_environmentmotorDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("motor.h");
  G__cpp_reset_tagtablemotorDict();
}
#include <new>
extern "C" int G__cpp_dllrevmotorDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Motor */
static int G__motorDict_177_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Motor* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Motor(
*((const string*) G__int(libp->para[0])), (int) G__int(libp->para[1])
, (Motor::AXES) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) Motor(
*((const string*) G__int(libp->para[0])), (int) G__int(libp->para[1])
, (Motor::AXES) G__int(libp->para[2]));
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Motor(*((const string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) Motor(*((const string*) G__int(libp->para[0])), (int) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Motor(*((const string*) G__int(libp->para[0])));
     } else {
       p = new((void*) gvp) Motor(*((const string*) G__int(libp->para[0])));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new Motor[n];
       } else {
         p = new((void*) gvp) Motor[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new Motor;
       } else {
         p = new((void*) gvp) Motor;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__motorDictLN_Motor));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const Motor*) G__getstructoffset())->status());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->activeAxes());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->posX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->posY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->posZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->speedX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->speedY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->speedZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->minPosX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->minPosY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->minPosZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->maxPosX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->maxPosY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->maxPosZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setSpeed((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setSpeed((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setSpeed((int) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setSpeed());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->moveAbsolute((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->moveRelative((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMinPositions((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMinPositions((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMinPositions((int) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMinPositions());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMaxPositions((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMaxPositions((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMaxPositions((int) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setMaxPositions());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->setActiveAxes((Motor::AXES) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->referenceRun());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((Motor*) G__getstructoffset())->clearRAM());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((const Motor*) G__getstructoffset())->dump();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const Motor*) G__getstructoffset())->semId());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Motor*) G__getstructoffset())->setDebug((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__motorDict_177_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = Motor::strError((char) G__int(libp->para[0]));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__motorDict_177_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Motor* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Motor(*(Motor*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__motorDictLN_Motor));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Motor G__TMotor;
static int G__motorDict_177_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Motor*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Motor*) (soff+(sizeof(Motor)*i)))->~G__TMotor();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Motor*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Motor*) (soff))->~G__TMotor();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__motorDict_177_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Motor* dest = (Motor*) G__getstructoffset();
   *dest = *(Motor*) libp->para[0].ref;
   const Motor& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Motor */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmotorDict {
 public:
  G__Sizep2memfuncmotorDict(): p(&G__Sizep2memfuncmotorDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmotorDict::*p)();
};

size_t G__get_sizep2memfuncmotorDict()
{
  G__Sizep2memfuncmotorDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemotorDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemotorDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__motorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__motorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__motorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__motorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__motorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__motorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__motorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__motorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__motorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__motorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("AXES",117,G__get_linked_tagnum(&G__motorDictLN_MotorcLcLAXES),0,G__get_linked_tagnum(&G__motorDictLN_Motor));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Motor */
static void G__setup_memvarMotor(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__motorDictLN_Motor));
   { Motor *p; p=(Motor*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__motorDictLN_MotorcLcLAXES),-1,-2,1,G__FastAllocString(2048).Format("X=%lldLL",(long long)Motor::X).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__motorDictLN_MotorcLcLAXES),-1,-2,1,G__FastAllocString(2048).Format("XY=%lldLL",(long long)Motor::XY).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__motorDictLN_MotorcLcLAXES),-1,-2,1,G__FastAllocString(2048).Format("XZ=%lldLL",(long long)Motor::XZ).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__motorDictLN_MotorcLcLAXES),-1,-2,1,G__FastAllocString(2048).Format("XYZ=%lldLL",(long long)Motor::XYZ).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,G__defined_typename("key_t"),-2,1,G__FastAllocString(2048).Format("s_sem_key=%lldLL",(long long)Motor::s_sem_key).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"d_status=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_deviceNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__motorDictLN_MotorcLcLAXES),G__defined_typename("AXES"),-1,4,"d_activeAxes=",0,(char*)NULL);
   G__memvar_setup((void*)0,73,0,0,-1,-1,-1,4,"d_posX=",0,(char*)NULL);
   G__memvar_setup((void*)0,73,0,0,-1,-1,-1,4,"d_posY=",0,(char*)NULL);
   G__memvar_setup((void*)0,73,0,0,-1,-1,-1,4,"d_posZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_speedX=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_speedY=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_speedZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_minPosX=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_minPosY=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_minPosZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_maxPosX=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_maxPosY=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_maxPosZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_fd=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,-1,-1,4,"d_error=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("ssize_t"),-1,4,"d_bufferSize=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,-1,-1,4,"d_buffer[128]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"d_semId=",0,(char*)NULL);
   G__memvar_setup((void*)0,89,0,0,-1,-1,-1,4,"d_shmPtr=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"d_debug=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmotorDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMotor(void) {
   /* Motor */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__motorDictLN_Motor));
   G__memfunc_setup("Motor",529,G__motorDict_177_0_1, 105, G__get_linked_tagnum(&G__motorDictLN_Motor), -1, 0, 3, 1, 1, 0, 
"u 'string' - 10 '\"/dev/ttyS0\"' tty i - - 0 '0' deviceNumber "
"u 'Motor::AXES' 'Motor::AXES' 0 'XZ' activeAxes", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("status",676,G__motorDict_177_0_2, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("activeAxes",1037,G__motorDict_177_0_3, 105, G__get_linked_tagnum(&G__motorDictLN_MotorcLcLAXES), G__defined_typename("Motor::AXES"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("posX",426,G__motorDict_177_0_4, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("posY",427,G__motorDict_177_0_5, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("posZ",428,G__motorDict_177_0_6, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("speedX",617,G__motorDict_177_0_7, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("speedY",618,G__motorDict_177_0_8, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("speedZ",619,G__motorDict_177_0_9, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("minPosX",718,G__motorDict_177_0_10, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("minPosY",719,G__motorDict_177_0_11, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("minPosZ",720,G__motorDict_177_0_12, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("maxPosX",720,G__motorDict_177_0_13, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("maxPosY",721,G__motorDict_177_0_14, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("maxPosZ",722,G__motorDict_177_0_15, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setSpeed",829,G__motorDict_177_0_16, 103, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 '100' x i - - 0 '100' y "
"i - - 0 '100' z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("moveAbsolute",1270,G__motorDict_177_0_17, 103, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - x i - - 0 - y "
"i - - 0 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("moveRelative",1267,G__motorDict_177_0_18, 103, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - dx i - - 0 - dy "
"i - - 0 - dz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMinPositions",1592,G__motorDict_177_0_19, 103, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 '0' x i - - 0 '0' y "
"i - - 0 '0' z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMaxPositions",1594,G__motorDict_177_0_20, 103, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 '6600' x i - - 0 '0' y "
"i - - 0 '8000' z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setActiveAxes",1337,G__motorDict_177_0_21, 103, -1, -1, 0, 1, 1, 1, 0, "u 'Motor::AXES' 'Motor::AXES' 0 - activeAxes", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("referenceRun",1252,G__motorDict_177_0_22, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("clearRAM",743,G__motorDict_177_0_23, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("dump",438,G__motorDict_177_0_24, 121, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("semId",498,G__motorDict_177_0_25, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDebug",819,G__motorDict_177_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - on", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("strError",867,G__motorDict_177_0_27, 117, G__get_linked_tagnum(&G__motorDictLN_string), -1, 0, 1, 3, 1, 0, "c - - 0 - error", (char*)NULL, (void*) G__func2void( (string (*)(char))(&Motor::strError) ), 0);
   G__memfunc_setup("readPosition",1265,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sendCommand",1129,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 1, 1, 4, 0, "C - - 10 - command", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Motor_strError",1491,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 1, 1, 4, 1, "c - - 0 - error", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getAxesString",1352,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__motorDictLN_string), -1, 0, 1, 3, 4, 0, "u 'Motor::AXES' 'Motor::AXES' 0 - d_activeAxes", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("comm_init",959,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 1, 1, 4, 0, "i - - 0 - chan", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("init_semaphore",1495,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("lockRS232",741,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("unlockRS232",968,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Motor", 529, G__motorDict_177_0_36, (int) ('i'), G__get_linked_tagnum(&G__motorDictLN_Motor), -1, 0, 1, 1, 1, 0, "u 'Motor' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Motor", 655, G__motorDict_177_0_37, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__motorDict_177_0_38, (int) ('u'), G__get_linked_tagnum(&G__motorDictLN_Motor), -1, 1, 1, 1, 1, 0, "u 'Motor' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmotorDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmotorDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmotorDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__motorDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__motorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__motorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__motorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__motorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__motorDictLN_Motor = { "Motor" , 99 , -1 };
G__linked_taginfo G__motorDictLN_MotorcLcLAXES = { "Motor::AXES" , 101 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemotorDict() {
  G__motorDictLN_string.tagnum = -1 ;
  G__motorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__motorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__motorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__motorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__motorDictLN_Motor.tagnum = -1 ;
  G__motorDictLN_MotorcLcLAXES.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemotorDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__motorDictLN_string);
   G__get_linked_tagnum_fwd(&G__motorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__motorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__motorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__motorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__motorDictLN_Motor),sizeof(Motor),-1,263424,(char*)NULL,G__setup_memvarMotor,G__setup_memfuncMotor);
   G__get_linked_tagnum_fwd(&G__motorDictLN_MotorcLcLAXES);
}
extern "C" void G__cpp_setupmotorDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmotorDict()");
  G__set_cpp_environmentmotorDict();
  G__cpp_setup_tagtablemotorDict();

  G__cpp_setup_inheritancemotorDict();

  G__cpp_setup_typetablemotorDict();

  G__cpp_setup_memvarmotorDict();

  G__cpp_setup_memfuncmotorDict();
  G__cpp_setup_globalmotorDict();
  G__cpp_setup_funcmotorDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmotorDict();
  return;
}
class G__cpp_setup_initmotorDict {
  public:
    G__cpp_setup_initmotorDict() { G__add_setup_func("motorDict",(G__incsetup)(&G__cpp_setupmotorDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmotorDict() { G__remove_setup_func("motorDict"); }
};
G__cpp_setup_initmotorDict G__cpp_setup_initializermotorDict;

