/********************************************************************
* motorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error motorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemotorDict();
extern void G__cpp_setup_inheritancemotorDict();
extern void G__cpp_setup_typetablemotorDict();
extern void G__cpp_setup_memvarmotorDict();
extern void G__cpp_setup_globalmotorDict();
extern void G__cpp_setup_memfuncmotorDict();
extern void G__cpp_setup_funcmotorDict();
extern void G__set_cpp_environmentmotorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "motor.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__motorDictLN_string;
extern G__linked_taginfo G__motorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__motorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__motorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__motorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__motorDictLN_Motor;
extern G__linked_taginfo G__motorDictLN_MotorcLcLAXES;

/* STUB derived class for protected member access */
