
#define SETPRESCALER 		 0
#define SETPACERCLOCK 		 1
#define SETOUTPUTCLOCK 		 2
#define SETCURVE 		 3
#define SETUPDATEGROUP 		 4
#define CLEARUPDATEGROUP 		 5
#define SETCLOCKSOURCE 		 6
#define SETOUTPUTCLOCKGENERATION 		 7
#define CLEAROUTPUTCLOCKGENERATION 		 8
#define STARTPACER 		 9
#define STOPPACER 		 10
#define GETPACER		 11
#define SETCYCLE 		 12
