#ifndef __TIDY_PROTOS_H__
#define __TIDY_PROTOS_H__

#include <Rtypes.h>
#include "../../tidy/inc/tidyenum.h"

//_________________________________________________________[C DEFINITION FILE]
//////////////////////////////////////////////////////////////////////////////
// Name:           tidy_protos.h
// Purpose:        C interface to tidy calls
// Description:    C prototypes for tidy
// Author:         R. Lutter
// Revision:       $Id: tidy_protos.h,v 1.1 2004-11-16 15:13:19 rudi Exp $       
// Date:           
// URL:            
// Keywords:       
//////////////////////////////////////////////////////////////////////////////

typedef void * TidyDoc;
typedef void * TidyOption;
typedef void * TidyNode;
typedef void * TidyAttr;
typedef void * TidyIterator;

struct _TidyBuffer 
{
    Char_t * bp;
    UInt_t size;
    UInt_t allocated;
    UInt_t next;
};
typedef struct _TidyBuffer TidyBuffer;

extern "C"  TidyDoc     tidyCreate(void);
extern "C"  void        tidyRelease(TidyDoc tdoc);
extern "C"  Int_t         tidyStatus(TidyDoc tdoc);
extern "C"  Int_t         tidyDetectedHtmlVersion(TidyDoc tdoc);
extern "C"  Bool_t        tidyDetectedXhtml(TidyDoc tdoc);
extern "C"  Bool_t        tidyDetectedGenericXml(TidyDoc tdoc);
extern "C"  UInt_t        tidyErrorCount(TidyDoc tdoc);
extern "C"  UInt_t        tidyWarningCount(TidyDoc tdoc);
extern "C"  UInt_t        tidyAccessWarningCount(TidyDoc tdoc);
extern "C"  Int_t         tidySetErrorBuffer(TidyDoc tdoc, TidyBuffer * errbuf);
extern "C"  UInt_t        tidyConfigErrorCount(TidyDoc tdoc);
extern "C"  Int_t         tidyLoadConfig(TidyDoc tdoc, Char_t * configFile);
extern "C"  Bool_t        tidyFileExists(Char_t * filename);
extern "C"  TidyOptionId  tidyOptGetIdForName(Char_t * optnam);
extern "C"  TidyIterator  tidyGetOptionList(TidyDoc tdoc);
extern "C"  TidyOption    tidyGetNextOption(TidyDoc tdoc, TidyIterator* pos);
extern "C"  TidyOption    tidyGetOption(TidyDoc tdoc, TidyOptionId optId);
extern "C"  TidyOption    tidyGetOptionByName(TidyDoc tdoc, Char_t * optnam);
extern "C"  TidyOptionId  tidyOptGetId(TidyOption opt);
extern "C"  Char_t *       tidyOptGetName(TidyOption opt);
extern "C"  TidyOptionType tidyOptGetType(TidyOption opt);
extern "C"  Bool_t          tidyOptIsReadOnly(TidyOption opt);
extern "C"  Char_t *       tidyOptGetDefault(TidyOption opt);
extern "C"  ULong_t         tidyOptGetDefaultInt(TidyOption opt);
extern "C"  Bool_t          tidyOptGetDefaultBool(TidyOption opt);
extern "C"  Char_t *       tidyOptGetValue(TidyDoc tdoc, TidyOptionId optId);
extern "C"  Bool_t          tidyOptSetValue(TidyDoc tdoc, TidyOptionId optId, Char_t * val);
extern "C"  Bool_t          tidyOptParseValue(TidyDoc tdoc, Char_t * optnam, Char_t * val);
extern "C"  ULong_t         tidyOptGetInt(TidyDoc tdoc, TidyOptionId optId);
extern "C"  Bool_t          tidyOptSetInt(TidyDoc tdoc, TidyOptionId optId, ULong_t val);
extern "C"  Bool_t          tidyOptGetBool(TidyDoc tdoc, TidyOptionId optId);
extern "C"  Bool_t          tidyOptSetBool(TidyDoc tdoc, TidyOptionId optId, Bool_t val);
extern "C"  Bool_t          tidyOptResetToDefault(TidyDoc tdoc, TidyOptionId opt);
extern "C"  Bool_t          tidyOptResetAllToDefault(TidyDoc tdoc);
extern "C"  TidyIterator  tidyOptGetDeclTagList(TidyDoc tdoc);
extern "C"  Int_t         tidyParseFile(TidyDoc tdoc, Char_t * filename);
extern "C"  Int_t         tidyParseStdin(TidyDoc tdoc);
extern "C"  Int_t         tidyParseString(TidyDoc tdoc, Char_t * content);
extern "C"  Int_t         tidyCleanAndRepair(TidyDoc tdoc);
extern "C"  Int_t         tidyRunDiagnostics(TidyDoc tdoc);
extern "C"  Int_t         tidySaveFile(TidyDoc tdoc, Char_t * filename);
extern "C"  Int_t         tidySaveStdout(TidyDoc tdoc);
extern "C"  Int_t         tidySaveBuffer(TidyDoc tdoc, TidyBuffer* buf);
extern "C"  Int_t         tidyOptSaveFile(TidyDoc tdoc, Char_t * cfgfil);
extern "C"  void        tidyErrorSummary(TidyDoc tdoc);
extern "C"  void        tidyGeneralInfo(TidyDoc tdoc);
extern "C"  TidyNode    tidyGetRoot(TidyDoc tdoc);
extern "C"  TidyNode    tidyGetHtml(TidyDoc tdoc);
extern "C"  TidyNode    tidyGetHead(TidyDoc tdoc);
extern "C"  TidyNode    tidyGetBody(TidyDoc tdoc);
extern "C"  TidyNode    tidyGetParent(TidyNode tnod);
extern "C"  TidyNode    tidyGetChild(TidyNode tnod);
extern "C"  TidyNode    tidyGetNext(TidyNode tnod);
extern "C"  TidyNode    tidyGetPrev(TidyNode tnod);
extern "C"  TidyAttr    tidyAttrFirst(TidyNode tnod);
extern "C"  TidyAttr    tidyAttrNext(TidyAttr tattr);
extern "C"  Char_t *     tidyAttrName(TidyAttr tattr);
extern "C"  Char_t *     tidyAttrValue(TidyAttr tattr);
extern "C"  TidyNodeType tidyNodeGetType(TidyNode tnod);
extern "C"  Char_t *     tidyNodeGetName(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsText(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsProp(TidyDoc tdoc, TidyNode tnod);
extern "C"  Bool_t tidyNodeIsHeader(TidyNode tnod);
extern "C"  Bool_t tidyNodeHasText(TidyDoc tdoc, TidyNode tnod);
extern "C"  Bool_t tidyNodeGetText(TidyDoc tdoc, TidyNode tnod, TidyBuffer* buf);
extern "C"  TidyTagId tidyNodeGetId(TidyNode tnod);
extern "C"  UInt_t tidyNodeLine(TidyNode tnod);
extern "C"  UInt_t tidyNodeColumn(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsHTML(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsHEAD(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsTITLE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsBASE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsMETA(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsBODY(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsFRAMESET(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsFRAME(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsIFRAME(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsNOFRAMES(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsHR(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsH1(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsH2(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsPRE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsLISTING(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsP(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsUL(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsOL(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsDL(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsDIR(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsLI(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsDT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsDD(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsTABLE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsCAPTION(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsTD(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsTH(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsTR(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsCOL(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsCOLGROUP(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsBR(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsA(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsLINK(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsB(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsI(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSTRONG(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsEM(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsBIG(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSMALL(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsPARAM(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsOPTION(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsOPTGROUP(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsIMG(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsMAP(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsAREA(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsNOBR(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsWBR(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsFONT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsLAYER(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSPACER(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsCENTER(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSTYLE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSCRIPT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsNOSCRIPT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsFORM(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsTEXTAREA(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsBLOCKQUOTE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsAPPLET(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsOBJECT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsDIV(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSPAN(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsINPUT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsQ(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsLABEL(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsH3(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsH4(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsH5(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsH6(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsADDRESS(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsXMP(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSELECT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsBLINK(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsMARQUEE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsEMBED(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsBASEFONT(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsISINDEX(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsS(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsSTRIKE(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsU(TidyNode tnod);
extern "C"  Bool_t tidyNodeIsMENU(TidyNode tnod);
extern "C"  TidyAttrId tidyAttrGetId(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsEvent(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsProp(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsHREF(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsSRC(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsID(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsNAME(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsSUMMARY(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsALT(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsLONGDESC(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsUSEMAP(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsISMAP(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsLANGUAGE(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsTYPE(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsVALUE(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsCONTENT(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsTITLE(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsXMLNS(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsDATAFLD(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsWIDTH(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsHEIGHT(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsFOR(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsSELECTED(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsCHECKED(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsLANG(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsTARGET(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsHTTP_EQUIV(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsREL(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnMOUSEMOVE(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnMOUSEDOWN(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnMOUSEUP(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnCLICK(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnMOUSEOVER(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnMOUSEOUT(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnKEYDOWN(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnKEYUP(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnKEYPRESS(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnFOCUS(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsOnBLUR(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsBGCOLOR(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsLINK(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsALINK(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsVLINK(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsTEXT(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsSTYLE(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsABBR(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsCOLSPAN(TidyAttr tattr);
extern "C"  Bool_t tidyAttrIsROWSPAN(TidyAttr tattr);
extern "C"  TidyAttr tidyAttrGetHREF(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetSRC(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetID(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetNAME(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetSUMMARY(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetALT(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetLONGDESC(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetUSEMAP(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetISMAP(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetLANGUAGE(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetTYPE(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetVALUE(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetCONTENT(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetTITLE(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetXMLNS(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetDATAFLD(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetWIDTH(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetHEIGHT(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetFOR(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetSELECTED(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetCHECKED(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetLANG(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetTARGET(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetHTTP_EQUIV(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetREL(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnMOUSEMOVE(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnMOUSEDOWN(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnMOUSEUP(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnCLICK(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnMOUSEOVER(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnMOUSEOUT(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnKEYDOWN(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnKEYUP(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnKEYPRESS(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnFOCUS(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetOnBLUR(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetBGCOLOR(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetLINK(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetALINK(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetVLINK(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetTEXT(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetSTYLE(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetABBR(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetCOLSPAN(TidyNode tnod);
extern "C"  TidyAttr tidyAttrGetROWSPAN(TidyNode tnod);

#endif
